name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
    - env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build an image
      run: |
          docker build ../ -t nataly00/docker_exercise
    - name: docker push
      run: |
          docker push nataly00/docker_exercise
